### ISSUE TITLE
[general] - Break; participation in side project

### ISSUE THREAD

**Issue by Vasc01** [Vasc01/file-compression-exercise#7]
**Parts needed**

- [x] - M3 flat/countersunk socket screws
- [ ] - Cable hoses 
- [x] - M3 nuts
- [x] - M2.5 screws cylinder head
- [x] - Two springs inner diameter 3+ mm x 30+ mm
- [x] - Clamps for platform
- [x] - Superglue

**Tasks** 

- [x] - pulley gt2 20t 4mm bore
- [x] - Assemble 3D printer
- [x] - Install Rhino and transfer license
- [x] - Order build plate and extruder front plates
- [x] - Find turner for bushings 
- [x] - Send out stls to Plamen 
- [ ] - set up machine when motors arrive

**3D Model** 

- [x] - Bushings for axes-pulleys x4 spiral mode 
- [x] - Adapter plates maxon – nema x2 
- [x] - Pillow 
- [x] - Leg 
- [x] - Z block mount 
- [x] - Z stop block 
- [x] - Rail stoppers 
- [x] - EVA parts 
- [x] - Pen holder
- [x] - Build plate cover dxf
